### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [MicheleBertoli/react-gmaps#1]
for react.rocks -- thanks!

**Comment by MicheleBertoli** [comment]
I <3 react.rocks!
Online demo is the next thing in my todo list, I'll let you know.
Thanks!

**Comment by winkler1** [comment]
Awesome, thanks!

**Comment by MicheleBertoli** [comment]
Here is the demo: 3f2ca2d9989e9f0c33ca412957413872804ae7b0
