### ISSUE TITLE
Custom KML layers

### ISSUE THREAD

**Issue by gabrielHosino** [MicheleBertoli/react-gmaps#100]
I give the user the option to upload a kml file, is it possible to show that on the map?

**Comment by MicheleBertoli** [comment]
Thanks for opening the issue #100 @gabrielHosino 
With this package, you can potentially do everything you do using the regular the Gmap SDK.
For example, the `onMapCreated` callback gives you the `map` object which you can use to do something like this:
```js
var ctaLayer = new google.maps.KmlLayer({
  url: 'http://googlemaps.github.io/js-v2-samples/ggeoxml/cta.kml',
  map: map
}); 
```
Please let me know if you need more information.
