### ISSUE TITLE
using gmaps polyline 

### ISSUE THREAD

**Issue by geraldsamosir** [MicheleBertoli/react-gmaps#101]
can i use google maps polyline  in this package ? if yes, can you give some example  ? for use it or maybe modification this package

**Comment by MicheleBertoli** [comment]
Hello @geraldsamosir, any feature of the Google Maps SDK works with this package.
The `onMapCreated` callback gives you the actual `map` instance, which you can use to do whatever you need, for example:

```js
handleMapCreated(map) {
  const flightPlanCoordinates = [
    {lat: 37.772, lng: -122.214},
    {lat: 21.291, lng: -157.821},
    {lat: -18.142, lng: 178.431},
    {lat: -27.467, lng: 153.027},
  ]
  const flightPath = new google.maps.Polyline({
    path: flightPlanCoordinates,
    geodesic: true,
    strokeColor: '#FF0000',
    strokeOpacity: 1.0,
    strokeWeight: 2,
  })

  flightPath.setMap(map)
},

render() {
  return (
    <Gmaps
      width={'50%'}
      height={'500px'}
      lat={21.291}
      lng={-157.821}
      zoom={2}
      onMapCreated={this.handleMapCreated} />
  )
}
```

<img width="513" alt="screen shot 2017-06-07 at 06 50 14" src="https://user-images.githubusercontent.com/1308971/26864021-bfa0c6de-4b4d-11e7-904b-8912aa0f3296.png">
