### ISSUE TITLE
How can i disable the zooming.

### ISSUE THREAD

**Issue by Abrinlouis** [MicheleBertoli/react-gmaps#106]
I need to disable the zomming when scrolling on the map.Please help me to solve this issue

**Comment by copperstick6** [comment]
Hey @Abrinlouis,
This is what your Maps Component should look like if you want to disable the scroll wheel:
```
<Gmaps
        //other settings here
        scrollwheel = {false}
 </Gmaps>
```

I've tested this solution and it should work. Let me know if you run into any more issues.

**Comment by Abrinlouis** [comment]
Thanks you..It worked

**Comment by Abrinlouis** [comment]
My map is showing blank at the first time,but when try to inspect or resize the window map is showing up.
Can you please help me sort this issue

**Comment by MicheleBertoli** [comment]
Thanks @copperstick6.

@Abrinlouis can you please provide a non-working example? Are you setting width and height?

**Comment by MicheleBertoli** [comment]
Thank you very much @copperstick6.

@Abrinlouis closing this in favor of #107
