### ISSUE TITLE
Map is showing blank

### ISSUE THREAD

**Issue by Abrinlouis** [MicheleBertoli/react-gmaps#107]
The map is not showing at the inital time.When we try to inspect or if the window size is changed,the map is showing up

**Comment by Abrinlouis** [comment]
<Gmaps onClick={this.showPropertDetailPage}
            width={'350px'}
            height={'450px'}
            lat={ lat }
            lng={ long }
            zoom={12}
            params={params}
            scrollwheel={false}
           onMapCreated={this.onMapCreated}
          viewport={true}>
          <Marker
                    lat={ lat }
                    lng={ long }
            /> </Gmaps>

**Comment by copperstick6** [comment]
Sample code?

**Comment by copperstick6** [comment]
Going off your sample code that you edited here:
```
<Gmaps onClick={this.showPropertDetailPage}
width={'350px'}
height={'450px'}
lat={ lat }
lng={ long }
zoom={12}
params={params}
scrollwheel={false}
onMapCreated={this.onMapCreated}
viewport={true}>
```
Make sure that you have closed off the GMaps component with `</Gmaps>`. Assuming that you've done that, take a look at the network section and make sure that it's loading.  
If it has been loading, make sure that there's not an error with your logic in your onMapCreated method. That tends to cause an error. If you can post your implementation here, that'd be great.

**Comment by Cumquat** [comment]
This may actually be to do with Google Maps. I had a similar problem with maps not showing when they were in a Bootstrap Tab Content. I created a function that was fired when the Tab menu was clicked and the map then showed.
`window.google.maps.event.trigger(this.theMap, 'resize');`
Hope this helps.

**Comment by MicheleBertoli** [comment]
Thanks @copperstick6 @Cumquat.
