### ISSUE TITLE
Custom Markers

### ISSUE THREAD

**Issue by sonsoleslp** [MicheleBertoli/react-gmaps#110]
Is there any way to provide a custom react component as a GMap child (a custom marker) ?

**Comment by copperstick6** [comment]
I'm not sure exactly what you're trying to ask, but I'll try my best.  
You can directly use the google maps javascript package to add custom markers. I recall there being a method to create a custom marker using google.maps.SYMBOL. After creating the marker, as long as you have the map instance, you can just use setMap to add it to the map, which will update with the marker.

**Comment by MicheleBertoli** [comment]
[Here](https://github.com/MicheleBertoli/react-gmaps/issues/53) it is an example of how to customize the markers.
I hope it helps.

Thanks @copperstick6.

**Comment by sonsoleslp** [comment]
Thanks so much! That's exactly what I meant!
