### ISSUE TITLE
Marker event listener for infoWindow

### ISSUE THREAD

**Issue by hermawan22** [MicheleBertoli/react-gmaps#112]
Hi, it's possible if there have a feature for open infowindow when click on marker?

Thanks man for your great job. 👍

**Comment by copperstick6** [comment]
Hey!  
One way you could design your markers to do so is to just use the maps API. Here's how you would do it.  
```
var marker = .... //initialize marker here.
marker.addListener('click', function(){
   var infowindow = ... //initialize infowindow here
   infowindow.setMap(map)   //where map is your map instance
});
marker.setMap(map)   //where map is your map instance   

```  
Let me know if you run into any more issues.

**Comment by MicheleBertoli** [comment]
Thank you very much for opening the issue @hermawan22 and @copperstick6 for suggesting a solution.
Here is also a similar issue #40 with an example.
I hope this helps.

**Comment by hermawan22** [comment]
Thanks for your response @MicheleBertoli  and suggest me [#40](url).
But the position is still not appropriate with marker (still cover the marker).
And if possible could you suggest me, how to share event between difference component on react without any state management?
Component1 trigger event -> Component2 listen the triggered event.
Component1 and Component2 don't have any relation (totally different component).
My case is i want trigger the click event marker on different component.
Thanks @MicheleBertoli. :)

@copperstick6 thanks man. :)
```
const marker = ...
marker.addListener("click", () => {
  infoWindow.open(map, marker);
});
```
I have been did it with just google maps API, it will be more useful if any feature for it in here. 👍

**Comment by MicheleBertoli** [comment]
For the position of the `InfoWindow`, you can use `pixelOffset={new google.maps.Size(0, -40)}`.
While to trigger the `InfoWindow` from a different component, you can use the "closest common ancestor" (see [Lifting State Up](https://facebook.github.io/react/docs/lifting-state-up.html)).

Here is a demo:

![infowindow](https://user-images.githubusercontent.com/1308971/30082357-6cf341ba-9282-11e7-8168-c962f32c1a48.gif)

And here is the [source](https://gist.github.com/MicheleBertoli/a7c510e9c665e052edfff49bec97a794) code.

I hope this helps @hermawan22.

**Comment by hermawan22** [comment]
Thanks @MicheleBertoli, this is what i looking for.
Very helpful and once again thanks for your help and your kindness. 👍
