### ISSUE TITLE
How to drop marker with a click

### ISSUE THREAD

**Issue by thehatami** [MicheleBertoli/react-gmaps#120]
i cant find any document about how i can drop a pin to map by user click. how can i do it?

**Comment by maulberto3** [comment]
Hi. Try conditional rendering and a custom method.

**Comment by MicheleBertoli** [comment]
Thank you very much @thehatami @maulberto3.
This is not something you'll find in the documentation as it's not specific to this package.

However, I built a simple demo to show you a potential approach to this problem.

![click](https://user-images.githubusercontent.com/1308971/39687822-f3082e32-51c7-11e8-9059-f4a6caf0862d.gif)

[Source](https://gist.github.com/MicheleBertoli/605f43b0f0b44515ac1f5264ff0a2e4e)

I hope this helps.
