### ISSUE TITLE
Map Label

### ISSUE THREAD

**Issue by ojcloveu** [MicheleBertoli/react-gmaps#124]
Could you add this to react-gmaps?
https://www.npmjs.com/package/js-map-label
we need it very much. or can u show me the say to implement it with reat-gmaps please

**Comment by MicheleBertoli** [comment]
Thanks for asking, @ojcloveu.

The original repo seems to be archived at the moment.
I'm closing this but please feel free to re-open it if you are still interested, it might be a good addition to v2 (#130).
