### ISSUE TITLE
Outdated React

### ISSUE THREAD

**Issue by cristianoccazinsp** [MicheleBertoli/react-gmaps#129]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

Please update the library to handle updated react versions.

**Comment by MicheleBertoli** [comment]
Thanks for opening this issue, @cristianoccazinsp 

Addressed in #130 
Please install `react-gmaps@next` to try the newest version of the library
