### ISSUE TITLE
Map is not re-rendering

### ISSUE THREAD

**Issue by RobinMalfait** [MicheleBertoli/react-gmaps#14]
Hello

I have this problem that I'm drawing a circle on the map, the circle radius can change and thus the props change.
Can you fix it that the map is re-rendered when props change?

Thanks

**Comment by MicheleBertoli** [comment]
Hey @RobinMalfait,

I just released an [update](https://github.com/MicheleBertoli/react-gmaps/blob/master/src/components/entity.js#L17) where the sub-components (Marker and InfoWindow) re-renders (updates their options) when the props change.
I'll do the same for the Gmaps component.

To be sure that this will fix your problem, can I please ask you how you are drawing the circle on the map?

Thanks!

**Comment by RobinMalfait** [comment]
@MicheleBertoli sure, my Circle component looks like this:

```
import React, { PropTypes } from 'react'

var Circle = React.createClass({
    propTypes: {
        lat: PropTypes.number.isRequired,
        lng: PropTypes.number.isRequired,
        radius: PropTypes.number
    },
    getDefaultProps() {
        return {
            radius: 0
        }
    },
    componentDidMount() {
        new google.maps.Circle({
            strokeColor: '#F44336',
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: '#F44336',
            fillOpacity: 0.35,
            map: this.props.map,
            center: new google.maps.LatLng(this.props.lat, this.props.lng),
            radius: this.props.radius
        })
    },
    render() {
        return null
    }
})

export default Circle
```

Also, I don't know if you forgot to update the package on npm, it is still at 0.2?

**Comment by MicheleBertoli** [comment]
I'm on it :)

![radius](https://cloud.githubusercontent.com/assets/1308971/9246789/d6a5158c-41a5-11e5-8132-24f0b03f3ebf.gif)

**Comment by RobinMalfait** [comment]
Oh man, push as soon as possible on npm!

I have been trying it myself with no luck but flickering google maps..

Thanks very much!

**Comment by RobinMalfait** [comment]
Awesome, only thing left is to update this :) https://www.npmjs.com/package/react-gmaps

**Comment by MicheleBertoli** [comment]
I was waiting for the Travis process to complete :)

0.3.0 is on npm now and this is a little demo for your circle:
https://gist.github.com/MicheleBertoli/85bb8de4504484620315
If you have any questions please ask me.

Thank you very much @RobinMalfait.

**Comment by RobinMalfait** [comment]
@MicheleBertoli  You sir, You are my hero!

Thank you very very much!

**Comment by urbantumbleweed** [comment]
I know this issue is closed but I appear to be having a similar issue. I have props being passed to the GMap object to create Markers.  When props updates that changes the number of markers, the map will not re-render.

The props being passed:
```javascript
render() {
    const {userLocation, trucks, actions, activeTruck, gmap} = this.props;
    const { setActiveTruck } = actions;

    // The markers that appear on the map
    // This can be moved to another component
    const truckMarkers = this.state.trucks.length ?
      map(this.state.trucks, (val) => {
        return <Marker
          lat={val.latitude}
          lng={val.longitude}
          key={val.objectId}
          onClick={(e) => {setActiveTruck(val.objectId)}}
          draggable={false}/>
      }) : null;

    // Using the infoWindow as external component is not working
    // Will put infoWindow inline for now
/*    const infoWindow = activeTruck ?
      <TruckInfoWindow activeTruck={activeTruck} /> : null*/


    // The info window that appears for the clicked truck
    const infoWindow = activeTruck ?
      <InfoWindow
        lat={activeTruck.latitude}
        lng={activeTruck.longitude}
        maxWidth={150}
        content={`<div class="active-truck__container">
          <h2 class="active-truck__name">${activeTruck.applicant}</h2>
          <p class="active-truck__item">
            <span class="active-truck__itemLabel">Location:</span>
            <span class="active-truck__location">${activeTruck.locationDescription}</span>
          </p>
          <p class="active-truck__item">
            <span class="active-truck__itemLabel">Hours:</span>
            <span class="active-truck__hours">${activeTruck.daysHours}</span>
          </p>
          <span class="active-truck__itemLabel">Items:</span>
          <ul class="active-truck__taglist">${map(activeTruck.tags, (tag, index) => {
            return (
              `<li class="active-truck__taglist__item" key=${index}>${tag}</li>`
            );
          }).join('')}</ul>
          </div>`} /> : null;

    // Use a conditional return
    // If the filter does not have trucks
    // then display message
    // ** workaround for issue that map will not render without markers **
    return ( this.state.trucks.length ?
      <Gmaps
        className='map'
        width={'100vw'}
        height={'100vh'}
        lat={userLocation.latitude}
        lng={userLocation.longitude}
        zoom={16}
        params={{v: '3.exp'}}
        props={this.props}
        onDragEnd={this.onMapDragEnd}
        onMapCreated={this.onMapCreated}>
        {truckMarkers}
        {infoWindow}
      </Gmaps> : <div className='no-results'>Hmm, we couldn't find anything.</div>
    );
  }
```

I have verified that I get the data I need and that the `<Markers /> components are being generated.  I have traced it to a non-rendering to a react method `processQueue()` that gets called and then screen starts a re-render but never finishes.  Any thoughts on what the problem could be or how I can fix this.

Any help you can provide would be great.

**Comment by MicheleBertoli** [comment]
Hey @urbantumbleweed,
thanks for your comment!

First of all: Are you using the latest version of the package ([1.4.3](https://github.com/MicheleBertoli/react-gmaps/releases/tag/1.4.3))?
If not, please upgrade it :)

Unfortunately I couldn't reproduce your problem ([source](https://gist.github.com/MicheleBertoli/6b9639b988d15453b49c)):
![markers](https://cloud.githubusercontent.com/assets/1308971/13598059/bf144c78-e513-11e5-8ab8-d9c92bc0f07c.gif)

Can you please share more code / give me more informations?

Have a nice day!
