### ISSUE TITLE
When going to another route, not re-rendering properly

### ISSUE THREAD

**Issue by RobinMalfait** [MicheleBertoli/react-gmaps#15]
Hello

Me again, I have found a new bug, maybe you know a solution.
When I got to a new route and go back, the map itself is not re-rendered but I see the Circle & Marker.

Circle & Marker are not centered but at position (0, 0) of the div (not the map itself)

Here is a video of the problem:

http://d.pr/v/14nEb

Thanks :)

**Comment by RobinMalfait** [comment]
@MicheleBertoli I'm sorry haha

**Comment by MicheleBertoli** [comment]
@RobinMalfait thank you very much!
I'll try to reproduce and fix it ;)

**Comment by RobinMalfait** [comment]
If I completely destroy the map it will work:

http://d.pr/v/18Qrq

Also, it would be nice to have the map re-zoom if the circle bounds are bigger:

this.map.zoom(circle.getBounds()) or something?

**Comment by MicheleBertoli** [comment]
hey @RobinMalfait 

can you please give me more informations about the way you are doing the routing?
[this simple demo](https://gist.github.com/MicheleBertoli/76e529302eee196dbb4d) with `react-router` is working

![routing](https://cloud.githubusercontent.com/assets/1308971/9256546/f4506be4-41e7-11e5-9d63-eed84b9d4ea3.gif)

if you don't mind, I would ask you to open a different issue for the `bounds` feature

thanks!

**Comment by RobinMalfait** [comment]
I'm using react-router as well

**Comment by MicheleBertoli** [comment]
It's weird, I hate non-reproducible bugs.
If you can give me more infos or code examples, I'll investigate deeper.

Also, If you upgrade the lib (0.3.1) and follow this example:
https://gist.github.com/MicheleBertoli/55b36359ce5b779990d6
You can update the bounds of the map according to the bounds of the circle.

![bounds](https://cloud.githubusercontent.com/assets/1308971/9260512/fdb5f862-41ff-11e5-8d8e-a4a2b6346c2f.gif)

**Comment by RobinMalfait** [comment]
@MicheleBertoli thanks for the bounds thingy!

I'm trying to make a simpler version with the bug, once I did it, I'll show you!

**Comment by RobinMalfait** [comment]
@MicheleBertoli Could it be that my data is too fast? 

I have a event listener when my page gets focus, it re-fetches my location and redraws the map, which works.
But it is not drawing when the data is already there.

When I resize the browser it is also re-rendering, it is very very weird...

**Comment by RobinMalfait** [comment]
@MicheleBertoli  I think that I found the bug! I have 2 maps, when the first is rendered, the second won't render correctly

**Comment by MicheleBertoli** [comment]
@RobinMalfait Interesting, thanks!
I'll try to reproduce it but if you could send me some code it would help a lot.
Have a nice day

**Comment by joschkarick** [comment]
I think I might have the same bug.

As soon as I use 2 GMaps components, neither of them works.
Here's the component:

```
import React from 'react';
import { Table } from 'react-bootstrap';
import { Gmaps } from 'react-gmaps';

const MapComponent = React.createClass({

  render() {

    return (
      <div>
        <Table striped>
          <tr><td>Descr</td><td>
            <Gmaps
              width="500px"
              height="500px"
              lat={51.929475}
              lng={7.174314}
              zoom={12} />
          </td></tr>
        </Table>
      </div>
    );
  },
});

export default MapComponent;
```

This is the console output from Chrome.

> Uncaught TypeError: m[md].maps.Load is not a function(anonymous function)
> @ main.js:70(anonymous function)
> @ main.js:71


I have 2 tabs which both include the component. If I include it on one tab only it's working perfectly fine.

Any ideas?

**Comment by MicheleBertoli** [comment]
Thanks @joschkarick, I have been able to reproduce it.
A fix will come soon ;)

**Comment by MicheleBertoli** [comment]
The version 0.4.0 solves this problem, thanks @RobinMalfait and @joschkarick

**Comment by RobinMalfait** [comment]
@MicheleBertoli perfect :)
