### ISSUE TITLE
Re-center on resize

### ISSUE THREAD

**Issue by RobinMalfait** [MicheleBertoli/react-gmaps#16]
Hey Man

It's me again, I was a bit afk due to exams, but I'm back!

Here is another issue I have, the map is not centered on resize, maybe you could make this an option?

This is something I've found 
https://gist.github.com/markthethomas/5da15a050f560cc58d4f

**Comment by MicheleBertoli** [comment]
hey @RobinMalfait,
good luck for your exams ;)

Thanks again for your suggestion.
In this case I just think that's a very project-specific feature and it shouldn't be inside the package.

Anyway, it's easy to do it: take a look [here](https://gist.github.com/MicheleBertoli/76f782b37ad779bd81cb).

**Comment by RobinMalfait** [comment]
Oh, perfect, thanks a lot :)
