### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by chiss2906** [MicheleBertoli/react-gmaps#17]
There is no way to make custom buttons (like replacing the zoom in/out icons), markers, color themes (e.g. https://snazzymaps.com/).

**Comment by MicheleBertoli** [comment]
Hey @chiss2906,
once the map is created, you can set any options.

 [This simple example](https://gist.github.com/MicheleBertoli/cbd07138c72ba3ad60e7) generates the following map:
<img width="413" alt="screen shot 2015-08-25 at 18 52 40" src="https://cloud.githubusercontent.com/assets/1308971/9474834/d4c26706-4b5a-11e5-9ba3-95447548741c.png">

**Comment by wmertens** [comment]
Wouldn't it be easier to provide map options to the GMap props?

**Comment by MicheleBertoli** [comment]
I would not say "easier" but we could do that.
It's all about making the Gmaps component accept all the options, like other components already do.
PRs are welcome :)

**Comment by wmertens** [comment]
Untested, would something like this work:

```js
createMap() {
  var center = !isNan(this.props.lat) ? new google.maps.LatLng(this.props.lat, this.props.lng): undefined;
  var googleOptions = assign({
      center: center
    }, this.props);
  this.map = new google.maps.Map(this.getDOMNode(), googleOptions);
...
```

That way it is both handy to use and supports all Google options...

Also, wouldn't it be better to pass the map to the `onMapCreated` callback?

**Comment by MicheleBertoli** [comment]
@wmertens [here](https://gist.github.com/MicheleBertoli/38c7f5e7214f5e5ead06) we go.
Thanks for your contributions.
