### ISSUE TITLE
Is there way to customize InfoWindow style, from javascript etc components ? 

### ISSUE THREAD

**Issue by rolandsusans** [MicheleBertoli/react-gmaps#19]
```javascript 
 {this.state.animateInfo.map(function(purchase){
                        var timeAgo = that.getPurchaseTimeAgo(purchase.created_at);
                        return (<InfoWindow
                            backgroundColor="#0989ff"
                            
                            lat={purchase.lat}
                            lng={purchase.long}
                            content={purchase.product_name +" " +timeAgo+"s ago"}
                            />);
})}
```
How can i apply custom style not using "hacky-css"?

**Comment by rolandsusans** [comment]
Ok, i found some workaround in plane JS, will it be possible using Marker to create something like this:
http://codepen.io/anon/pen/wKMExr

**Comment by MicheleBertoli** [comment]
hey @rolandsusans 

it's not really related to this package and I'm not sure what you mean by "hacky-css" but you can style your InfoWindow with regular CSS, like:

<img width="408" alt="screen shot 2015-09-15 at 20 38 23" src="https://cloud.githubusercontent.com/assets/1308971/9887936/318da2f8-5bea-11e5-8b62-67694e696fe6.png">

[source](https://gist.github.com/MicheleBertoli/5d52ef31573cfe11c8c8)

**Comment by ashishchoudhary12** [comment]
how to hide infow window close button???

**Comment by MicheleBertoli** [comment]
http://lmgtfy.com/?q=how+to+hide+infow+window+close+button%3F%3F%3F
