### ISSUE TITLE
Map not rerendered correctly after state change

### ISSUE THREAD

**Issue by sebprunier** [MicheleBertoli/react-gmaps#20]
Hi,

I use the Gmaps component this way : 
```jsx
<Gmaps
    ref="gmaps"
    height={'600px'}
    lat={parseFloat(this.state.quizz.districtInfoLat)}
    lng={parseFloat(this.state.quizz.districtInfoLon)}
    zoom={12}
    loadingMessage={'Chargement ...'}
    onMapCreated={this._onMapCreated}>
    <Marker
        lat={parseFloat(this.state.quizz.districtInfoLat)}
        lng={parseFloat(this.state.quizz.districtInfoLon)}
        draggable={false}/>
</Gmaps>
```

The state may be changing this way (by clicking a button) : 
```javascript
_loadNewQuizz() {
    Axios.get('/api/quizz/new').then(quizz => this.setState({
        quizz: quizz.data,
        quizzResult: null,
        selectedOption: null
    }));
}
```

When I click the button, the Marker rerenders correctly, but the map is not centered on the new lat and lon :-(

Did I miss something or is it a bug?

Thanks in advance for your help!
Sébastien

**Comment by MicheleBertoli** [comment]
Hey @sebprunier,
thank you very much for your feedback.

I pushed a new version of the library ([0.4.1](https://github.com/MicheleBertoli/react-gmaps/releases/tag/0.4.1)) in which the map updates according to the new props.

[Here](https://gist.github.com/MicheleBertoli/0f209fd6922ebec85626) is an example:
![center](https://cloud.githubusercontent.com/assets/1308971/10123088/38d6cbbc-6526-11e5-835b-27520df2d2cd.gif)

**Comment by sebprunier** [comment]
Great, it works now !
Thanks a lot !

(This was for a quizz about the districts of Nantes city (in France): http://nantes-quizz.cleverapps.io/quizz/district)

**Comment by MicheleBertoli** [comment]
Perfect, thanks!
