### ISSUE TITLE
Display directions

### ISSUE THREAD

**Issue by razagill** [MicheleBertoli/react-gmaps#23]
Hi @MicheleBertoli, is there a way we can render direction on the map e.g. supply a origin and destination locations and draw a path between them?

**Comment by MicheleBertoli** [comment]
Hello @razagill, 

the `onMapCreated` callback passes you the `map` object so you can use it to do any kind of operations you usually do with the Google Maps SDK.

If you could give me a more detailed explanation about what you are trying to do (for example, a link to the Google documentation), I'll be happy to create a simple demo for you.

Thanks,
Michele

**Comment by razagill** [comment]
Hi @MicheleBertoli, I was trying to implement https://developers.google.com/maps/documentation/directions/intro. But I guess that's a completely different api endpoint than the maps one. So it's more of an enhancement.

**Comment by MicheleBertoli** [comment]
Hello @razagill,

yes, that's a completely different API.

However, you could show the directions on the map using the [directions service](https://developers.google.com/maps/documentation/javascript/directions) and the map object provided by the `onMapCreated` callback.
See: https://developers.google.com/maps/documentation/javascript/examples/directions-simple

Thanks,
Michele
