### ISSUE TITLE
React 0.14.x support

### ISSUE THREAD

**Issue by nedzadk** [MicheleBertoli/react-gmaps#25]
I get following warning 
`Warning: Gmaps.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.` when upgraded to react 0.14.x. 
What is your plan on supporting react 0.14.x ?

**Comment by mewejo** [comment]
+1 ?

**Comment by MicheleBertoli** [comment]
Thank you very much @nedzadk @mewejo 
[1.1.0](https://github.com/MicheleBertoli/react-gmaps/releases/tag/1.1.0) is out, supporting react 0.14.

**Comment by mewejo** [comment]
Thanks!
