### ISSUE TITLE
Map recentering on new props

### ISSUE THREAD

**Issue by mewejo** [MicheleBertoli/react-gmaps#27]
Hey,

Just implementing this module, which is great!

One issue, when moving a marker and saving its location back to the state, it updates the props of the maps center.

Is there a way to stop the map from re-centering, I know you added code to make it happen, but it would be nice if it was optional please :)

Thanks!

**Comment by mewejo** [comment]
This is also affecting zoom of the map

**Comment by MicheleBertoli** [comment]
Thank you very much @mewejo 
You are right, I have been asked to update the map options **but** the component was updating the options too many times (even if they weren't changed).

Now the component is working as expected:
![drag](https://cloud.githubusercontent.com/assets/1308971/11181494/683c5718-8c5a-11e5-8acf-35f99efe3240.gif)
[source](https://gist.github.com/MicheleBertoli/2658419a7c65cdc4ad24)

Please install the version [1.2.0](https://github.com/MicheleBertoli/react-gmaps/releases/tag/1.2.0) from npm and let me know if it fixes your issue.
