### ISSUE TITLE
Using geolocation

### ISSUE THREAD

**Issue by dstockdale** [MicheleBertoli/react-gmaps#28]
Sorry this is more of a query than an issue I think but how would you go about using Geolocation (as per what's already available in the maps api?

https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

I'm trying to see if there's an event before the map is created but where the google maps api has been lazy loaded and can be used or maybe simply putting a step before loading the map to get the users location is the way to go? 

I basically want to use a users location if permitted/available and centre the map on that.

**Comment by MicheleBertoli** [comment]
Hey @dstockdale 

You can do it using the `onMapCreated` callback, like:

![geolocation](https://cloud.githubusercontent.com/assets/1308971/11562025/24110cf2-99c3-11e5-8bbf-42cf20686cf7.gif)
[source](https://gist.github.com/MicheleBertoli/c118522aa3f5a0c1e988)

As you can see in the Google's example, they first create the map (`new google.maps.Map`) and then ask for the current position (`geolocation.getCurrentPosition`).
So, you don't need an event fired before the map is created but you can use the event fired right after the map is created (`onMapCreated`).

**Comment by dstockdale** [comment]
Thanks @MicheleBertoli. I did figure this out but I'd got your library a bit confused with gmaps.js and their example http://hpneo.github.io/gmaps/examples/geolocation.html which is why I was asking the dumb question about events. Too many tabs open! I think this is a useful bit of info for people using your component though. Nice work thank you.
