### ISSUE TITLE
Cannot read property 'getMap' of undefined when using demo snippet

### ISSUE THREAD

**Issue by neilff** [MicheleBertoli/react-gmaps#3]
When I used the provided demo snippet:

```

  render() {
    return (
      <Gmaps 
        ref='Gmaps'
        width={'100%'}
        height={'100%'}
        lat={coords.lat} 
        lng={coords.lng} 
        zoom={12} 
        onMapCreated={this.onMapCreated}
        onClick={this.onClick}>
        <Marker 
          lat={coords.lat} 
          lng={coords.lng} />
      </Gmaps>
    );
  },

  onMapCreated() {
    console.log('onMapCreated', this.refs.Gmaps.getMap());
  }
```

I was getting `Cannot read property 'getMap' of undefined` when trying to access `this.refs.Gmaps`, I changed this to:

```
  render() {
    return (
              <Gmaps
                ref={ this.onMapCreated }
                width={'100%'}
                height={'100%'}
                lat={coords.lat}
                lng={coords.lng}
                zoom={12}
                onClick={this.onClick}>
                <Marker
                  lat={coords.lat}
                  lng={coords.lng} />
              </Gmaps>
    );
  },

  onMapCreated(component) {
    console.log('onMapCreated', component.getMap());
  }
```

And it fixed the issue. I assume it wasn't able to get the DOM reference previously. I can submit a PR if you think this is the correct approach.

**Comment by MicheleBertoli** [comment]
Hey @neilff, I can't reproduce the error.
If I just run the demo snippet, I get this `onMapCreated Zk {gm_bindings_: Object, __gm: Ii, gm_accessors_: Object, center: lf, zoom: 12…}` in the console.
Can you please provide me a full non-working example?
Thanks!

**Comment by neilff** [comment]
Interesting, I'm using Immutable, WebPack, Babel in my stack, I don't think that should cause any issues however... When I open source this project I'm working on, I can provide you the example of where it failed for me.

**Comment by loktar00** [comment]
This is happening with me as well I am using react-router wondering if something with that is causing issues. On refresh it always works perfectly, however when switching pages it doesn't.. still looking into it on my end, @neilff  fix didn't work for my case.

**Comment by MicheleBertoli** [comment]
Hey @loktar00, thanks for the feedback!
I absolutely want to fix that, can you please share with me a non-working example?
We are using both `react-gmaps` and `react-router` in production at [BIZZBY](https://www.bizzby.com) without any error, I really need help from you guys to find the problem.
Thanks!

**Comment by MicheleBertoli** [comment]
hey @neilff @loktar00 any news about this? Thanks!

**Comment by jnmandal** [comment]
I didn't get this exact error, but the problem could be that you need to bind this. Ie:

```
onMapCreated={this.onMapCreated.bind(this)}
```
I absent mindedly copy-pasted the example to play around and was getting a "Uncaught TypeError: Cannot read property 'Gmaps' of undefined" until I added the binding.

Using webpack with babel-loader and react-hot.

**Comment by MicheleBertoli** [comment]
Thanks @jnmandal, are you using es6 classes or did you just copy/paste the example on the readme?

**Comment by MicheleBertoli** [comment]
@neilff checking your `react-liqbo` repo, I found and fixed the problem. Thanks!

@jnmandal it looks like you are using ES6 Classes, right?

**Comment by jnmandal** [comment]
Yep, using ES6 classes.. Just realized you were using React's class constructor, that explains it!

**Comment by MicheleBertoli** [comment]
@jnmandal perfect, thanks!

**Comment by neilff** [comment]
@MicheleBertoli hey sorry, was away last few weeks, I'll take a look at the PR when I have a chance, thanks
