### ISSUE TITLE
How to best call fitBounds()?

### ISSUE THREAD

**Issue by pjsinco** [MicheleBertoli/react-gmaps#39]
Thank you for this making this component.

In my map, I need to dynamically set the bounds, using the `fitBounds()` method on the instance of `google.Maps.map`. The map instance is available in `onMapCreated().`

Is there a way to update my map (call `fitBounds()`) outside of the `onMapCreated()` method? For example, can I grab hold of the map instance in one of React's lifecycle methods? 

So, to recap, I need to call `fitBounds()` again, *after* the map is created.

I'm a bit of a newbie, so I apologize if there's an obvious answer to this question!

**Comment by MicheleBertoli** [comment]
Hello @pjsinco,
there are two easy ways to call a method on the map instance outside the `onMapCreated` callback:

1 - storing the instance inside the component's state:
```javascript
onMapCreated(map) {
  this.setState({map});
}
```
```javascript
this.state.map.fitBounds();
```

2 - accessing the Gmaps instance through the refs:
```jsx
<Gmaps ref="gmaps" />
```
```javascript
this.refs.gmaps.getMap().fitBounds();
```
(note: calling the `getMap` before the `onMapCreated` returns `null`)

Here is a working [example](https://gist.github.com/MicheleBertoli/cb00b7cadf06f8701610).

Hope this answers your question :)

**Comment by pjsinco** [comment]
Super helpful! I got it to work using that second method—thank you!
