### ISSUE TITLE
Register API key

### ISSUE THREAD

**Issue by jamiedumont** [MicheleBertoli/react-gmaps#43]
How would you recommend registering the required API key when using this package? 

There's obviously the `<script>` tag, but I'm unable to store the key in a private variable and append it to the URL within the HTML file.

Is there a way to do this from within the package?

**Comment by MicheleBertoli** [comment]
Hey @jamiedumont, 
the way I'm doing it in my apps is using the `params` prop of the `Gmap` components, like:

```
<Gmaps
  width={'800px'}
  height={'600px'}
  lat={coords.lat}
  lng={coords.lng}
  zoom={12}
  params={{key: 'yourKey1234567890'}}
>
```

**Comment by jamiedumont** [comment]
Sorry it took me a while to reply. Thanks very much for the help!
