### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by ilrein** [MicheleBertoli/react-gmaps#45]
Thanks for this great little library, do you guys mind explaining how to configure a legitimate API key here?

```Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys```

**Comment by MicheleBertoli** [comment]
Thanks for your question @ilrein, please have a look here: #43.
I'll update the documentation soon.
Have a nice day!
