### ISSUE TITLE
Help with InfoWindow

### ISSUE THREAD

**Issue by peterpetre** [MicheleBertoli/react-gmaps#47]
Hi there. I need some help with InfoWindow. I want to open a info window when i click on each marker. I have tried a lot of things but no luck until now.

**Comment by MicheleBertoli** [comment]
Hello @peterpetre, please check my comment on #40 and let me know if it solves your problem.
Have a nice day!

**Comment by peterpetre** [comment]
Hey, thanks it works fine! I got one more issue, i would like to setCenter when someone clicks on a marker with marker's lat lng. Have you implemented something like Gmaps.setCenter({lat: lat, lng: lng})?

**Comment by MicheleBertoli** [comment]
Hello @peterpetre, there are two ways to change the center of the map:

Updating the lan, lng props of the Gmaps component ([source](https://gist.github.com/MicheleBertoli/321d28c7103359e53592c9deec19dfe4))

![center](https://cloud.githubusercontent.com/assets/1308971/15090724/7f8fe7f2-1429-11e6-8c7a-62c6863916a9.gif)

Using `panTo` (animated) or `setCenter` directly on the map ([source](https://gist.github.com/MicheleBertoli/e5deb17b39a5a39f01631275fead8969))

![pan](https://cloud.githubusercontent.com/assets/1308971/15090713/1a2e7982-1429-11e6-8dcd-08fe35586698.gif)

**Comment by peterpetre** [comment]
Thanks it works great! I was about to ask you about positioning infowindow above the icon but i found a way.

```
<InfoWindow
          key={index}
          lat={coords.lat}
          lng={coords.lng}
          pixelOffset={new google.maps.Size(0, -40)}
          onCloseClick={() => this.toggleMarker(index)}
/>
```
