### ISSUE TITLE
Issue when installed as a dependency

### ISSUE THREAD

**Issue by martinaglv** [MicheleBertoli/react-gmaps#5]
Hey, thanks for the great module! A maps react component is desperately needed and yours is the only one which works with 0.13 as far as I can see.

However there is one small issue that prevents it from being used. When react-gmaps is installed as a dependency to another module, no devDependencies are installed from your package.json, and your module needs them to run. 

Maybe react and the babel-related modules can be moved to `dependencies`?

**Comment by MicheleBertoli** [comment]
Hey @martinaglv, thanks for the feedback.
I already removed all the dependencies in 1.6 (https://github.com/MicheleBertoli/react-gmaps/commit/014dd8a7bed2f5c59fbfc04bea1cc53003f2595c).
No breaking changes so I suggest you to upgrade the package.
Have a nice day!
