### ISSUE TITLE
Directions some help

### ISSUE THREAD

**Issue by peterpetre** [MicheleBertoli/react-gmaps#51]
Hello there, i trying to add directions on an already drawed map to minimize api requests. The think is directionsDisplay.setMap(map); needs the map object from onMapCreated(map). There is any way to use this map object outside of it onMapCreated? Like on ComponentDidUpdate or something? Or there is any other solution? So i can play with changing direction request and to doesnt have to redraw the map.

```
const start = new google.maps.LatLng(28.694004, 77.110291);
const end = new google.maps.LatLng(28.72082, 77.107241);

const directionsDisplay = new google.maps.DirectionsRenderer();
directionsDisplay.setMap(map); // map should be already initialized.

const request = {
        origin : start,
        destination : end,
        travelMode : google.maps.TravelMode.DRIVING
 };

const directionsService = new google.maps.DirectionsService(); 
directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
        }
 });
```

**Comment by MicheleBertoli** [comment]
Hey @peterpetre, is there any particular reason why you can't use the `onMapCreated` callback?
Thanks!

**Comment by peterpetre** [comment]
@MicheleBertoli i can use it, the thing is onMapCreated is called once when the map is created right? What i want to do is to create once the map and render the directions on it but i directions info will change. Maybe if somehow can i take the map object or if there is onMapChanged(map) method. I tried to dispatch the map object on store (redux) and use it on ComponentDidUpdate() but it badly crashed :)

**Comment by MicheleBertoli** [comment]
Ok @peterpetre.
What I suggest you to do is to set the map `directionsDisplay.setMap(map);` once with `onMapCreated` and then run `directionsService.route` anytime you need.
If for any reason you have to set the map again, you can always use the `getMap()` method: you just have to add `ref` prop to the `Gmaps` component and then you can access it like this `this.refs.yourMapRef.getMap()`.
Hope this helps.

**Comment by peterpetre** [comment]
@MicheleBertoli Hey thanks, so you suggest me to add 
```
const directionsDisplay = new google.maps.DirectionsRenderer();
directionsDisplay.setMap(map);
const directionsService = new google.maps.DirectionsService();
```
on onMapCreated? But how can i have access on these objects outside of onMapCreated?

```
**directionsService**.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
            **directionsDisplay**.setDirections(response);
        }
 });
```

**Comment by MicheleBertoli** [comment]
@peterpetre like this:
```javascript
onMapCreated(map) {
  this.directionsDisplay = new google.maps.DirectionsRenderer();
  directionsDisplay.setMap(map);
  this.directionsService = new google.maps.DirectionsService();
},
```
and then:
```javascript
onSomething() {
  this.directionsService.route(...);
},
```

**Comment by peterpetre** [comment]
@MicheleBertoli Thanks a lot thats what i needed, have a nice weekend!
