### ISSUE TITLE
Is there a way to change marker icons? 

### ISSUE THREAD

**Issue by em222iv** [MicheleBertoli/react-gmaps#53]
The setIcon function from the maps API is not included, so is there any way to alter a marker icon after it has been set? Could the setIcon functionality be implemented?
I have tried setting intervals for the new iconlinks to be provided but but not succeeded.

Best regards

**Comment by MicheleBertoli** [comment]
hey @em222iv

here we go:
![seticon](https://cloud.githubusercontent.com/assets/1308971/17620186/75f29442-6082-11e6-96fc-53a770f7db0f.gif)
[source](https://gist.github.com/MicheleBertoli/70eef44bcd607bef94a7b8197f86b68e)

hope this helps!

**Comment by em222iv** [comment]
Thanks!

**Comment by MatthewKosloski** [comment]
Is there a way to set the icon when the component mounts to prevent the default red icon from showing up?  I can't set the icon in `componentDidMount` because the `refs` are not defined.  I can do it in `componentDidUpdate`, but it only sets the icon if you click on the map.

**Comment by MicheleBertoli** [comment]
Hello @MatthewKosloski,
instead of applying the icon on `componentDidMount`, you could do:

```javascript
<Marker
  lat={lat}
  lng={lng}
  draggable={false}
  ref="marker"
  icon="assets/location.png"
/>
```

Hope this answers your questions.

**Comment by MatthewKosloski** [comment]
Oh, that works quite nicely. Thanks!

**Comment by avgDev0** [comment]
I have my map located in root/Map/index.js and my icons in root/Map/assets/ want to specify an icon for a marker like: 

`<Marker ...props icon="./assets/image.ico" />` and it doesn't seem to work, what am I missing?

UPDATE: I changed from .ico extension to .svg file and worked.
