### ISSUE TITLE
Get the zoom level

### ISSUE THREAD

**Issue by riccardolorenzon** [MicheleBertoli/react-gmaps#55]
hi, 

is it possible to get the current zoom level upon the `onZoomChanged` event?

i attached the event handler in this way : 

```
onZoomChanged={this.onZoomChanged}
```

but any parameter i add on that function results to be `undefined`.

**Comment by MicheleBertoli** [comment]
hello @riccardolorenzon 

the `zoom_changed` event is not passing any arguments:

![screen shot 2016-09-12 at 5 15 27 pm](https://cloud.githubusercontent.com/assets/1308971/18443451/e5d201ce-790c-11e6-9aad-65b0284d3a5e.png)

what you can do is to use the reference to the actual map instance:

```javascript
handleZoomChanged() {
  console.log('zoom:', this.refs.Gmaps.getMap().getZoom());
},
```

![zoom](https://cloud.githubusercontent.com/assets/1308971/18443476/fb182900-790c-11e6-85cc-36fdc9699f1e.gif)
[source](https://gist.github.com/MicheleBertoli/8108a9c47a6381cc36001b4113afa9e9)

hope this helps!

**Comment by riccardolorenzon** [comment]
Hi @MicheleBertoli, 

thank you for the quick answer. 

Unfortunately when i try to get the `refs` object i get this exception:
 
`Uncaught TypeError: Cannot read property 'getMap' of undefined`

Any idea?

**Comment by MicheleBertoli** [comment]
hey @riccardolorenzon,

it looks like you are using ES2015 classes and you forgot to bind the `handleZoomChanged` function in the constructor:

```javascript
constructor(props) {
  super(props)

  this.handleZoomChanged = this.handleZoomChanged.bind(this)
}
```

I hope this solves your problem, otherwise please share some code and I'll be happy to help you.

**Comment by riccardolorenzon** [comment]
hey @MicheleBertoli, 

i tried to bind the method but it didn't work. 

Yeah i'm using ES6 classes, i also tried with the ES5 syntax(like in your example), but it didn't work. 

this is the component i'm working on: https://github.com/riccardolorenzon/SF-Movies/blob/master/src/components/Map.js

**Comment by MicheleBertoli** [comment]
ok @riccardolorenzon 

so, if you set the ref as follows:
`ref={(googleMap) => this.gmap = googleMap}`

you then access the property with:
`this.gmap.getMap().getZoom()`

in my example I was doing:
`ref="Gmaps"`

and that's why the following was working:
`this.refs.Gmaps.getMap().getZoom()`

hope this helps!

**Comment by riccardolorenzon** [comment]
Yeah, it works! 

Grazie!!
