### ISSUE TITLE
 _reactDom2.default.findDOMNode is not a function

### ISSUE THREAD

**Issue by BobLamarley** [MicheleBertoli/react-gmaps#56]
Hi @MicheleBertoli ,
I'm new in React JS and i want to try your library for a project which consists in get position of an Arduino Card connected to a GPS sensor.
The problem is : I can't display the map, and i don't know why, maybe my react version is too old ? I'm in react v0.13

There is my code :
`
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import {Gmaps, Marker, InfoWindow, Circle} from 'react-gmaps';

const coords = {
  lat: 51.5258541,
  lng: -0.08040660000006028
};

const Data = React.createClass({

  onMapCreated(map) {
   map.setOptions({
     disableDefaultUI: true
   });
 },

 onDragEnd(e) {
   console.log('onDragEnd', e);
 },

 onCloseClick() {
   console.log('onCloseClick');
 },

 onClick(e) {
   console.log('onClick', e);
 },

  render: function() {
    return (
      <Gmaps
         width={'800px'}
         height={'600px'}
         lat={coords.lat}
         lng={coords.lng}
         zoom={12}
         loadingMessage={'Be happy'}
         params={{v: '3.exp', key: GOOGLEKEY}}
         onMapCreated={this.onMapCreated}>
         <Marker
           lat={coords.lat}
           lng={coords.lng}
           draggable={true}
           onDragEnd={this.onDragEnd} />
         <InfoWindow
           lat={coords.lat}
           lng={coords.lng}
           content={'Hello, React :)'}
           onCloseClick={this.onCloseClick} />
         <Circle
           lat={coords.lat}
           lng={coords.lng}
           radius={500}
           onClick={this.onClick} />
       </Gmaps>
    );
  }
});

class Suivi extends Component {

  render() {
    return (
`<div>`
 `<Data />`
    `</div>`
  );
  }
}

export default Suivi;

`

And in my console, i obtain this error :
gmaps.js:81 Uncaught TypeError: _reactDom2.default.findDOMNode is not a function

I already tried to update my react version but unfortunately some other part of my application depend on react v0.13

There is my dependencies in package.json :

`"dependencies": {
    "axios": "^0.7.0",
    "classnames": "^2.1.5",
    "express": "^4.13.3",
    "history": "1.17.0",
    "mongoose": "~3.6.13",
    "nodemailer": "^2.4.2",
    "uni-carousel-react": "^0.1.16",
    "react": "^0.13.3",
    "react-dom": "^15.2.1",
    "react-gmaps": "^1.5.0",
    "react-redux": "^2.1.2",
    "react-router": "^1.0.0-rc1",
    "redux": "^3.0.0",
    "redux-router": "^1.0.0-beta3",
    "redux-thunk": "^0.1.0"
  },
  "devDependencies": {
    "babel": "^5.8.21",
    "babel-core": "^5.8.22",
    "babel-loader": "^5.3.2",
    "redux-devtools": "^2.1.5",
    "redux-logger": "^2.0.2",
    "babel-plugin-react-transform": "^1.1.0",
    "babel-runtime": "^5.8.20",
    "webpack": "^1.11.0",
    "style-loader": "^0.8.0",
    "css-loader": "^0.9.0",
    "url-loader": "^0.5.6",
    "file-loader": "0.8.5",
    "react-transform-hmr": "^1.0.0",
    "webpack-dev-middleware": "^1.2.0",
    "webpack-hot-middleware": "^2.2.0",
    "merge": "^1.2.0",
    "extract-text-webpack-plugin": "^0.8.2"
  }`
It would be very helpful if you can help me, i'm blocked.
Have a good day :)
PS: Sorry for the code section, i have some trouble with github ^^

**Comment by MicheleBertoli** [comment]
Hello @BobLamarley ,
I'm sorry you have problems with the library.
My suggestion is to upgrade React because the version 0.13 is obsolete.

If for some reasons you can't do that, you may want to "downgrade" `react-gmaps` to the version `1.0.4` which uses React 0.13 and it should work.
Obviously, you are going to miss some features and some bug fixes.
