### ISSUE TITLE
Get the coordinates of Marker

### ISSUE THREAD

**Issue by MatthewKosloski** [MicheleBertoli/react-gmaps#57]
I tried doing `this.refs.Gmaps.refs.Marker.getPosition().lat()` but it says:

    Uncaught TypeError: this.refs.Gmaps.refs.Marker.getPosition is not a function

Does the Marker even have a method `getPosition()`?  Does this component have all the methods that a regular Marker would have, like in vanilla JS?  Thank you for making this;  all the other React Google Map components are **very** confusing!

My code:

	import React, { Component } from 'react';
	import {render} from 'react-dom';
	import {Gmaps, Marker, InfoWindow} from 'react-gmaps';

	class App extends Component {

		constructor() {
			super();
			this.state = {
				coords: {
					lat: 40.6319467,
	  				lng: -89.0465174
				}
			}
			this.onDragEnd = this.onDragEnd.bind(this);
			this.handleClick = this.handleClick.bind(this);
		}

		onMapCreated(map) {
			map.setOptions({
				disableDefaultUI: true
			});
		}

		onDragEnd(e) {
			console.log('dragged');
		}

		handleClick() {
			console.log(this.refs.Gmaps.refs.Marker.getPosition().lat());
		}

		render() {

			const { coords } = this.state;

			return (
				<div>
					<Gmaps
						width={'800px'}
						height={'600px'}
						lat={coords.lat}
						lng={coords.lng}
						zoom={8}
						loadingMessage={'Loading...'}
						params={{v: '3.exp', key: 'API_KEY_GOES_HEREEEE'}}
						onMapCreated={this.onMapCreated}
						ref="Gmaps">
						<Marker
							lat={coords.lat}
							lng={coords.lng}
							draggable={true}
							onDragEnd={this.onDragEnd} 
							ref="Marker"/>
					</Gmaps>
					<button onClick={this.handleClick}>Click</button>
				</div>
			);
		}
	}

	render(<App />, document.getElementById('root'));

**Comment by MatthewKosloski** [comment]
Spoke too soon, found out how.  I just think the problem is that I'm unfamiliar with the Google Maps API and have no idea where to look for documentation and such.

    this.refs.Gmaps.refs.Marker.getEntity().internalPosition.lat()
    this.refs.Gmaps.refs.Marker.getEntity().internalPosition.lng()

**Comment by MicheleBertoli** [comment]
Hello @MatthewKosloski 

there are two ways of doing it:

1) when the `dragend` event is fired you read the coordinates from the event (and you can save them into the local state to be reused later):
```jsx
  onDragEnd(e) {
    const { latLng } = e;
    console.log(latLng.lat());
    console.log(latLng.lng());
  }
```

2) when the button is clicked (or whenever you need it) you read the position from the entity:
```jsx
  handleClick() {
    const position = this.refs.Gmaps.refs.Marker.getEntity().getPosition();
    console.log(position.lat());
    console.log(position.lng());
  }
```

Hope this helps.
