### ISSUE TITLE
Add Polygon

### ISSUE THREAD

**Issue by tristandb** [MicheleBertoli/react-gmaps#58]
Polygon isn't currently added to the API of the project. Is this possible in the feature?

**Comment by tristandb** [comment]
Should be fixed in #59

**Comment by MicheleBertoli** [comment]
Hey @tristandb 
thanks for your issue and your PR.
I've just seen that you closed it, is there a reason for that?

**Comment by tristandb** [comment]
It was closed because some files weren't included during the commit. I'll add them soon. I've added Polyline as well.
