### ISSUE TITLE
React should be a peer dependancy

### ISSUE THREAD

**Issue by iest** [MicheleBertoli/react-gmaps#6]
Ran into [this issue](http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined).

Should just be a package change.

Also, shouldn't all the `dependancies` actually be `devDependancies`?

**Comment by MicheleBertoli** [comment]
Thanks @iest!
I fixed that in 1.6 (014dd8a7bed2f5c59fbfc04bea1cc53003f2595c)

**Comment by iest** [comment]
Derp!
