### ISSUE TITLE
Question: plotting json data

### ISSUE THREAD

**Issue by monski** [MicheleBertoli/react-gmaps#60]
Hi I'm just new to javascript. can you help me achieve this?

onMapCreated(map) {
    var flightPlanCoordinates = [
        {lat: 37.772, lng: -122.214},
        {lat: 21.291, lng: -157.821},
        {lat: -18.142, lng: 178.431},
        {lat: -27.467, lng: 153.027}
      ];
      this.refs.gmaps.Polyline({
          path: flightPlanCoordinates,
          geodesic: true,
          strokeColor: '#FF0000',
          strokeOpacity: 1.0,
          strokeWeight: 2
        });

  },
https://developers.google.com/maps/documentation/javascript/examples/polyline-simple

**Comment by MicheleBertoli** [comment]
hey @monski,
inside the `onMapCreated` callback you can use the map in the same way as the official example.

![screen shot 2016-09-28 at 08 31 45](https://cloud.githubusercontent.com/assets/1308971/18904520/4e6b2d5a-8556-11e6-84d9-4e43743028c3.png)


```javascript
  onMapCreated(map) {
    const flightPlanCoordinates = [
      { lat: 37.772, lng: -122.214 },
      { lat: 21.291, lng: -157.821 },
      { lat: -18.142, lng: 178.431 },
      { lat: -27.467, lng: 153.027 },
    ];

    const flightPath = new google.maps.Polyline({
      path: flightPlanCoordinates,
      geodesic: true,
      strokeColor: '#FF0000',
      strokeOpacity: 1.0,
      strokeWeight: 2,
    });

    flightPath.setMap(map);
  },
```

[source](https://gist.github.com/MicheleBertoli/b89695c63f2598347f2c2e9e28d0ad24)
