### ISSUE TITLE
Event `bounds_changed` is not firing up

### ISSUE THREAD

**Issue by riccardolorenzon** [MicheleBertoli/react-gmaps#61]
Hi, 

I'm trying to attach a listener for the `bounds_changed` event. 

In order to achieve this i add to the `Gmaps` object the event handler in this way :
```
<Gmaps
   [...]
   onBoundsChanged={this.onBoundsChanged} />
```

and obviously i create the handler: 

```
onBoundsChanged() {
    console.log('bounds change event!!');
  }
```

But i'm not getting any log. Any idea? 

Thanks

**Comment by MicheleBertoli** [comment]
Hey @riccardolorenzon,

the following code works for me:

```jsx
const App = React.createClass({

  onBoundsChanged() {
    console.log('bounds_changed');
  },

  render() {
    return (
      <Gmaps
        height={300}
        lat={51.5258541}
        lng={-0.08040660000006028}
        onBoundsChanged={this.onBoundsChanged}
        width={400}
        zoom={12}
      />
    );
  },

});
```

<img width="400" alt="screen shot 2016-09-29 at 06 17 39" src="https://cloud.githubusercontent.com/assets/1308971/18955631/0c30fe9e-860d-11e6-89f4-499bb8b0bcf4.png">

Can you please check again and see if there's something wrong somewhere else in your code?

**Comment by riccardolorenzon** [comment]
Hey @MicheleBertoli, 

Apparently i did the same as you can see [here](https://github.com/riccardolorenzon/SF-Movies/blob/master/src/components/Map.js) , it does not work though. 

I'm quite sure it's a trivial issue, but i cannot really figure it out.

**Comment by MicheleBertoli** [comment]
I think i found the problem:

```jsx
onZoomChanged={this.onZoomChanged.bind(this)}>
onBoundsChanged={this.onBoundsChanged}
```

At line [72](https://github.com/riccardolorenzon/SF-Movies/blob/master/src/components/Map.js#L72) you have an extra `>`.

**Comment by riccardolorenzon** [comment]
ooops!! 

thanks!
