### ISSUE TITLE
"map.setOptions is not a function"

### ISSUE THREAD

**Issue by FidelisClayton** [MicheleBertoli/react-gmaps#65]
"map.setOptions is not a function" when i'm trying to set map styles;

``` javascript
    handleMapLoad(map) {
        this._mapComponent = map; 
        map.getZoom(); // 15
        map.setOptions({styles: MAP_STYLE}); // "map.setOptions is not a function"
    }
```

**Comment by MicheleBertoli** [comment]
Hello @FidelisClayton,
I'm not able to reproduce your error, can you please give me more information?
I'll be happy to help!

**Comment by FidelisClayton** [comment]
Here's my code:

``` javascript
// imports ...

import { MAP_STYLE } from 'shared/constants';


const Map = withGoogleMap(props => {
	return (
		<GoogleMap 
			{...{styles: MAP_STYLE}}
		    defaultZoom={props.zoom}
		    center={props.center}
		    onClick={props.onMapClick}
		    styles={MAP_STYLE}
			ref={props.onMapLoad}
		>
			<Marker {...props.marker} />

		</GoogleMap>
	);
});

export default class NovoLocal extends Component {
	// constructor and others functions ...

    handleMapLoad(map) {
        this._mapComponent = map;
        map.setOptions({styles: MAP_STYLE}); // "map.setOptions is not a function"
    }

    render() {
        

        return (
			<div className="row">
				
				<div className="col-md-9 map-wrapper">
					<Map
						marker={this.props.marker}
						onMapClick={this.handleMapClick.bind(this)}
						zoom={this.props.zoom}
						center={this.props.center}
						onMapLoad={this.handleMapLoad.bind(this)} // <----
						title={"Teste"}
					    containerElement={
					      <div style={{ height: `100%` }} />
					    }
					    mapElement={
					      <div style={{ height: `100%`, position: 'absolute', width: '100%' }} />
					    }
					/>
				</div>
			</div>
	    );
	}
}
```

The **"Map"** component doesn't have the "setOption" function, so how can i apply a new style to my map? 

Following this docs: https://developers.google.com/maps/documentation/javascript/styling?hl=pt-br

**Comment by MicheleBertoli** [comment]
Oh, now I can see the problem @FidelisClayton.
You are using the ref of the Map component you created as if it was the Google Map object (which is not).
Not sure what `withGoogleMap` does but the callback you have to use is `onMapCreated`, please check the example in the [README](https://github.com/MicheleBertoli/react-gmaps#usage)

**Comment by FidelisClayton** [comment]
i'm so embarrassed, i was using a wrong component (tomchentw/react-google-maps). Thanks for your help and i'm so sorry for this issue. BTW, now i'm using your component, it sounds great!
