### ISSUE TITLE
Question: Multiple Marker Color

### ISSUE THREAD

**Issue by monski** [MicheleBertoli/react-gmaps#66]
Hello,

Just want to ask if i can change the marker on the defined position?
Sample: i want on the point 2, the marker will be the green, and the the rest is circle
`<Gmaps
                ref="gmaps"
                params={{v: '3.exp', key: variables.gmapsApi}}
                width={'auto'}
                height={'600px'}
                lat={this.state.clickPoints.lat}
                lng={this.state.clickPoints.lng}
                onMapCreated={this.onMapCreated}
                zoom={this.state.gmapsZoom}>
                {this.state.pointsResult.length > 0 ? (
                  this.state.pointsResult.map((g,i) => {
                    let icon = {
                      path: google.maps.SymbolPath.CIRCLE,
                      strokeColor: '#FF0000',
                      fillColor: '#FF0000',
                      fillOpacity: 0.8,
                      scale: 5
                    }
                    if(g.package_status ==null) {
                    return (
                      <Marker icon={icon} onClick={() => this.toggleInfoWindow(i,g)} key={`marker-${i}`} lat={g.lat} lng={g.lng} />
                    )
                  } else {
                    let colorIcon = "http://maps.google.com/mapfiles/ms/icons/green-dot.png"
                    return (
                    <Marker icon={colorIcon} onClick={() => this.toggleInfoWindow(i,g)} key={`marker-${i}`} lat={g.lat} lng={g.lng} />
                    )
                  }
                  })
                  ) : null }
                {this.state.pointsResult.length > 0 ? (
                  this.renderInfoWindows()
              ) : null }
              </Gmaps>`

Thanks in advance.

**Comment by MicheleBertoli** [comment]
Hello @monski,
not sure I understand your questions but the following demo should help:

<img width="407" alt="screen shot 2016-10-25 at 19 30 09" src="https://cloud.githubusercontent.com/assets/1308971/19699048/937625fa-9ae9-11e6-8179-e334b843da08.png">
[source](https://gist.github.com/MicheleBertoli/89a35d07c7b51c347b7a99b549752d51)

Please let me know if you have any other questions.

**Comment by monski** [comment]
Hello Michele,
thanks for the reply, i figured it out also that it needs two separate array of the position for that..
 thanks again
