### ISSUE TITLE
Question : About build.js

### ISSUE THREAD

**Issue by ofostier** [MicheleBertoli/react-gmaps#68]
Hello Michele,

I'm trying to use react-gmaps but i don't understand where the build.js come from.
If i download the source and write it near the index.js, it works

Thx

**Comment by MicheleBertoli** [comment]
Hello @ofostier,
I guess the `build.js` you are talking about is the demo one, right?
It comes from this [script](https://github.com/MicheleBertoli/react-gmaps/blob/master/package.json#L11).

But I don't think you should care about it if you want to use the library.
Please run `npm install --save react-gmaps` and then use `const { Gmaps } from 'react-gmaps'` in your application.

Hope this helps!

**Comment by ofostier** [comment]
Thanks Michele for your feed back

The error is between my chair and my laptop ....

Really thx
