### ISSUE TITLE
Marker Icons

### ISSUE THREAD

**Issue by mteichtahl** [MicheleBertoli/react-gmaps#69]
Is it possible to change the Icon with this component ?

I have tried the code below with no luck

 <Marker
                          key={index.toString() + '.1'}
                          label={data.city}
                          name={data.city}
                          position={{ lat: data.lat, lng: data.lng }}
                          icon="https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png"
                          onClick={self.onMarkerClick.bind(self)} />
                      )

**Comment by MicheleBertoli** [comment]
Hello @mteichtahl, please have a look at the issue #53, it should answer your question.
