### ISSUE TITLE
Add option to allow disable componentWillReceiveProps actions

### ISSUE THREAD

**Issue by phibsholo** [MicheleBertoli/react-gmaps#70]
Hi!! 
When I was using your component I found an interaction that I don't need. When gmaps component receive props, do a centering map and for me it was horrible, because the new prop that I add is a new info window and I want that don't miss the focus. 
For this reason I do next change in your code and works good without affecting your current behaviour.

I did this change into `react-gmaps/dist/components/gmaps.js`

```javascript
componentWillReceiveProps: function componentWillReceiveProps(nextProps) {
  if (!this.props.disableWillReceiveProps && this.map && !(0, _utilsCompareProps2['default'])(this.props, nextProps)) {
    this.map.setOptions(_extends({}, nextProps, {
      center: new google.maps.LatLng(nextProps.lat, nextProps.lng)
    }));
  }
},
```

And into my code I did:

```javascript
<Gmaps
  width={'100%'}
  height={'100%'}
  lat="41.382294"
  lng="2.172245"
  zoom="14"
  disableWillReceiveProps
  params={{ v: '3.exp', key: 'api_key' }}
>
  {this.state.infoWindow}
</Gmaps>
```

When I do a `this.setState({ infoWindow })` it's added a new `<InfoWindow />` that doesn't affect to current map.

I hope that if you think that is a good idea you will add it.

**Comment by MicheleBertoli** [comment]
Hello @phibsholo, thanks for opening the issue.

There are two reasons why the map is moving back to its center when the info window gets added:

1) you are passing an object to the map as `params` that gets newly created on each render and it causes the map to refresh.

See example 1 ([source](https://gist.github.com/MicheleBertoli/91d98a0f3a9b8204c7f97d86c229faf1)):

![1](https://cloud.githubusercontent.com/assets/1308971/20244489/adf1afb6-a97c-11e6-95b9-97138c8a031b.gif)

You tried to fix it with `disableWillReceiveProps` but you could easily avoid the problem by "extracting" the params from the render:

```javascript
const params = { v: '3.exp', key: 'api_key' }
```
And using the same object all the time:

```javascript
<Gmaps
  width={'100%'}
  height={'100%'}
  lat="41.382294"
  lng="2.172245"
  zoom="14"
  params={params}
>
```

2) as you may have noticed, the maps is still moving to make the info window visible.

See example 2 ([source](https://gist.github.com/MicheleBertoli/9d1fb215466f6f74ca4e7cd7205ece0a)):

![2](https://cloud.githubusercontent.com/assets/1308971/20244497/ff6e8fe4-a97c-11e6-8156-7c367bcf3f5f.gif)

This is the default behaviour of the Google Maps and there an option that you can use to change it:

<img width="675" alt="screen shot 2016-11-13 at 08 43 54" src="https://cloud.githubusercontent.com/assets/1308971/20244509/64ac09cc-a97d-11e6-91df-d658ba821931.png">

See example 3 ([source](https://gist.github.com/MicheleBertoli/9099fa80766bf73d6660b8cdb342ac49)):

![3](https://cloud.githubusercontent.com/assets/1308971/20244516/b26d56f2-a97d-11e6-9ed7-2683b53548df.gif)

Hope this helps :)

**Comment by phibsholo** [comment]
Hello Michele, 

Thanks for the fast answer, but I have to comment to you that this solution doesn't solve my problem... because I create the info window when user do a click into a marker.. and the new window appears in the same markers latitude-longitude, and if user did a zoom, it will be lost.

I tried a lot of manners to draw the window to avoid the center effects, but anything solves except skipping componentWillReceiveProps.

Step 1: Initial Map

```
const 
   markers = markersList.map(
      function(marker, index) {
         return <Marker
            key={index}
            name={marker.name}
            lat={marker.lat}
            lng={marker.lng}
            onClick={this.onMarkerClick.bind(this)} />
      }, this);
```
```
<Gmaps
   width={'100%'}
   height={'100%'}
   lat={info.map.lat}
   lng={info.map.lng}
   zoom={info.map.zoom}
   loadingMessage={''}
   params={{v: '3.exp', key: info.map.api_key}}
>
   {markers}
   {this.state.infoWindow}
</Gmaps>
```

![initial-map](https://cloud.githubusercontent.com/assets/9462636/20259225/0ee001a6-aa54-11e6-851c-283c05b64f3b.png)

Step 2: Do zoom

![zoom](https://cloud.githubusercontent.com/assets/9462636/20259234/19d3b166-aa54-11e6-970e-a2e36bed5d9b.png)

Step 3: Click on marker

```
onMarkerClick () {

   const { marker } = this.props;

   const windowHTML = map.getWindowHTML(marker);

   var infoWindow = <InfoWindow
      lat={marker.lat}
      lng={marker.lng}
      onCloseClick={this.onCloseInfoWindow.bind(this)}
      content={windowHTML} />;

   this.setState({ infoWindow });
}
```

![show-info](https://cloud.githubusercontent.com/assets/9462636/20259256/2e0ee272-aa54-11e6-8013-8d195c2596f6.png)

**Comment by MicheleBertoli** [comment]
Hello @phibsholo,

> I tried a lot of manners to draw the window to avoid the center effects, but anything solves except skipping componentWillReceiveProps.

From what I can see in your code:

```javascript
<Gmaps
  width={'100%'}
  height={'100%'}
  lat={info.map.lat}
  lng={info.map.lng}
  zoom={info.map.zoom}
  loadingMessage={''}
  params={{v: '3.exp', key: info.map.api_key}}
>
```

You are still creating the `params` object on each render, which causes the re-centering.

As I suggested in my point 1):

> you could easily avoid the problem by "extracting" the params from the render

As you can see in the following gif, creating the `params` once outside the render and using it on each render fixes the problem without needing to hack into `componentWillReceiveProps`.

![4](https://cloud.githubusercontent.com/assets/1308971/20259821/d8487b82-aa4e-11e6-85a1-89c97450a91e.gif)

Here it is the [source code](https://gist.github.com/MicheleBertoli/3b43412f1b05b90719b3c98680a9923f), please make sure to check the way I'm passing the `params` to the `Gmaps` component.

**Comment by phibsholo** [comment]
Aaaaa!!! it's true... sorry!! 

I will try it!! thanks a lot!!!

**Comment by phibsholo** [comment]
It works!!! Thanks a lot ;)

**Comment by MicheleBertoli** [comment]
You are welcome @phibsholo 
I'm very happy it works as expected now
