### ISSUE TITLE
Help: Adding SearchBox for places..

### ISSUE THREAD

**Issue by monski** [MicheleBertoli/react-gmaps#71]
Hello can you help me add a searchbox on gmaps?

i did this on:

  onMapCreated(map) {
    var input = document.getElementById(  document.getElementById('searchmap') );
    var searchBox = new google.maps.places.SearchBox(input);

but getting error "Uncaught TypeError: Cannot read property 'SearchBox' of undefine"

thanks in advance

**Comment by monski** [comment]
Sorry for the post... i figured it out already, adding key in params of the component...

thanks

**Comment by n1cklarosa** [comment]
Are you able to post an example of your working code? I cant get a searchbox happening at all.

**Comment by monski** [comment]
Hi,

get the sample code here:
https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

then on React Gmaps

`const Maps = React.createClass({
  Gmaps: {},
onMapCreated(map) {
      let input = this.refs.searchmap
      let searchBox = new google.maps.places.SearchBox(input);
// and some of the code from the lin
`
then add a params in Gmaps component
  params={{v: '3.exp', key: "YOUR_API_KEY, libraries: 'places'}}

**Comment by n1cklarosa** [comment]
thanks!
