### ISSUE TITLE
How do I set the language for the map?

### ISSUE THREAD

**Issue by ryananglem** [MicheleBertoli/react-gmaps#72]
In the google maps API it describes a language setting here:

`  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap&language=ja&region=JP"
    async defer>`

I've tried adding the language attribute to the params eg.

`{v: '3.exp', key:process.env.REACT_APP_GOOGLE_MAP_KEY, language:'fr'};`

.. but this does not work. Where should I put it?

**Comment by MicheleBertoli** [comment]
Hello @ryananglem,

I've tried this:

```javascript
const App = () => (
  <Gmaps
    width={400}
    height={300}
    lat={51.5258541}
    lng={-0.08040660000006028}
    zoom={12}
    params={{ language: 'ja', region: 'JP' }}
  />
);
```

And it seems to work:

<img width="415" alt="screen shot 2016-11-29 at 21 46 04" src="https://cloud.githubusercontent.com/assets/1308971/20730272/586a3910-b67d-11e6-8b30-f62a7d584429.png">

**Comment by ryananglem** [comment]
Thanks. It seems that the map was being translated to French by selecting 'fr' - it kept all the English street names which confused me, but translated the terms and conditions message and other system type text which I didn't immediately notice.
