### ISSUE TITLE
Markers spanning multiple tiles are split

### ISSUE THREAD

**Issue by dancormier** [MicheleBertoli/react-gmaps#80]
In Safari (10.0.3), map pins that span multiple tiles have a 1px missing portion where tiles meet.

![2017-01-25_167x113](https://cloud.githubusercontent.com/assets/647177/22308540/6a3b588a-e315-11e6-88cf-bbe4057bb15d.png)

This is remedied in the inspector by setting `overflow: visible` of tile on left side of split, but I'm not sure how to actually fix this.

**Comment by MicheleBertoli** [comment]
The library doesn't do anything on top of the Google Maps SDK in order to render the marker.
Can you please verify whether you have the same issue without using the component @dancormier ?

**Comment by dancormier** [comment]
Closing this issues, since this is a in fact Google Maps issue specific to Safari. Found this example on an example not using this plugin. 
![2017-01-27_131x101](https://cloud.githubusercontent.com/assets/647177/22377451/ff416346-e47f-11e6-971a-3f10c61b8f67.png)
