### ISSUE TITLE
How to render React component in InfoWindow content?

### ISSUE THREAD

**Issue by feux07** [MicheleBertoli/react-gmaps#85]
Hi everyone,

How to render React component in InfoWindow content? When I use ReactDOMServer.renderToString() method it is possible but events are not working with this way. As an example I prepared to this online webpackbin. [https://www.webpackbin.com/bins/-KeUKeaOdpWnBZT9qFl8](https://www.webpackbin.com/bins/-KeUKeaOdpWnBZT9qFl8)  When you click button in info window, onClick event not working.

Thanks
(Sorry for my bad English)

**Comment by MicheleBertoli** [comment]
Hello @feux07!

Unfortunately `renderToString` does not activate the event handlers, and there are no other ways to render React components inside an InfoWindow at the moment.

PRs are welcome :)
