### ISSUE TITLE
Change Circle color

### ISSUE THREAD

**Issue by IronTony** [MicheleBertoli/react-gmaps#87]
Hello,

is there a way to change the Circle and the border color?
Best and thank you in advance.

**Comment by MicheleBertoli** [comment]
Sure @IronTony,
all the [options](https://developers.google.com/maps/documentation/javascript/reference#CircleOptions) of the Circle class work.

```js
<Circle
  fillColor="green"
  lat={coords.lat}
  lng={coords.lng}
  radius={500}
  strokeColor="blue"
/>
```

<img width="421" alt="screen shot 2017-03-25 at 13 17 52" src="https://cloud.githubusercontent.com/assets/1308971/24322520/9940faa6-115d-11e7-992b-84d8d1ca25ca.png">

**Comment by IronTony** [comment]
Awesome, thank you!
Another question I forgot. Is it also possibile to change the style of the external line in dashed, dotted style?

**Comment by MicheleBertoli** [comment]
You can apply all the style changes allowed by the Google Maps SDK.
