### ISSUE TITLE
Zoom level according to markers

### ISSUE THREAD

**Issue by umairfarooq44** [MicheleBertoli/react-gmaps#92]
I want to make all the markers visible on the map. How can I set zoom level automatically to make all markers visible on the map all the time, regardless of the distance between markers and no. of markers?

**Comment by MicheleBertoli** [comment]
In the `onMapCreated` callback you receive the instance of the map, at that point you should be able to follow this: http://stackoverflow.com/a/19304625/1712895
Please let me know if you need more help.

**Comment by umairfarooq44** [comment]
Thanks a lot for providing solution. My issue has been solved. Please close this issue
