### ISSUE TITLE
Passing children to InfoWindow

### ISSUE THREAD

**Issue by malexandrum** [MicheleBertoli/react-gmaps#99]
Michele,
Could you add support for specifying children to the InfoWindow component? I know you have the 'content' prop on it, but I need to pass a link that is handled by a react method on click, and that's not possible with the content prop I guess. Should be pretty straight forward to support children, isn't it?

Thank you.

**Comment by MicheleBertoli** [comment]
This doesn't seem straightforward but if you think it is please submit a PR, I'll be happy to review it.
At the moment this feature is not supported, see #85.
